# === Environment & PATH ===
export EDITOR=nvim
export VISUAL=nvim
export BROWSER=google-chrome-stable
export PAGER="bat -p --color auto"
export TERMINAL=kitty
export TERM="xterm-256color"

export GPG_TTY=$TTY

# Dedicated Ripgrep config
export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME/ripgrep/ripgreprc"


# === History ===
HISTFILE=~/.zsh_history
HISTSIZE=100000
SAVEHIST=100000
setopt APPEND_HISTORY SHARE_HISTORY HIST_IGNORE_DUPS HIST_IGNORE_SPACE HIST_EXPIRE_DUPS_FIRST HIST_FIND_NO_DUPS

# === Shell Options ===
setopt extended_glob null_glob AUTOCD NUMERIC_GLOB_SORT

# === Keybindings & Line Editor ===
bindkey -e # Emacs mode

bindkey '^[[1~' beginning-of-line    # Home
bindkey '^[[H'  beginning-of-line    # Home
bindkey '^[[3~' delete-char          # Delete
bindkey '^[[4~' end-of-line          # End
bindkey '^[[F'  end-of-line          # End
bindkey '^[[5~' up-line-or-history   # PageUp
bindkey '^[[6~' down-line-or-history # PageDown
bindkey '^?'    backward-delete-char # Backspace

bindkey '^[[1;5C' forward-word       # Ctrl + Right
bindkey '^[[1;5D' backward-word      # Ctrl + Left

autoload -Uz up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

bindkey '^[[A' up-line-or-beginning-search
bindkey '^[[B' down-line-or-beginning-search

autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^X^E' edit-command-line
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward

# === Cache Setup ===
local cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/inits"
[[ -d "$cache_dir" ]] || mkdir -p "$cache_dir"

(( $+functions[compdef] )) || compdef() { : }

# Init function with cache invalidation
load_cached_init() {
  local cmd="$1" cache_file="$cache_dir/$1.zsh"
  shift

  local bin_path="$(whence -p "$cmd")"
  [[ -n "$bin_path" ]] || return 1

  # Rebuild if cache is missing or binary is newer
  if [[ ! -f "$cache_file" || "$bin_path" -nt "$cache_file" ]]; then
    "$bin_path" "$@" > "$cache_file"
  fi
  # echo "$cmd"
  source "$cache_file"
}

# Loading CLI tools & completions before Zinit
load_cached_init mise activate zsh

# === Zinit Plugins ===
ZINIT_HOME="${XDG_DATA_HOME}/zinit/zinit.git"
source "$ZINIT_HOME/zinit.zsh"

# Direct load to prevent first-prompt render delay
zinit light zsh-users/zsh-autosuggestions

# Defered plugins
zinit wait lucid for \
  atinit"zicompinit; zicdreplay" \
    zdharma-continuum/fast-syntax-highlighting \
    zsh-users/zsh-completions

# Completion styling & Autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=8"
ZSH_AUTOSUGGEST_STRATEGY=(history completion)

zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]-_}={[:upper:][:lower:]_-}' 'r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu select

(( $+commands[fast-theme] )) && fast-theme XDG:catppuccin-macchiato -q
zle_highlight=('paste:none')

load_cached_init dircolors -b
load_cached_init fzf --zsh
# load_cached_init oh-my-posh init zsh --config "$XDG_CONFIG_HOME/ohmyposh/skillarch.toml"
load_cached_init oh-my-posh init zsh --config "$XDG_CONFIG_HOME/ohmyposh/clomic.toml"
load_cached_init zoxide init zsh
load_cached_init atuin init zsh --disable-up-arrow
load_cached_init register-python-argcomplete --no-defaults exegol
load_cached_init wt config shell init zsh

# === Aliases, Hooks & Helpers ===
[[ -f ~/.my_aliases ]] && source ~/.my_aliases
[[ -f /opt/skillarch/config/aliases ]] && source /opt/skillarch/config/aliases

# Colored man/help pages via bat
man() { GROFF_NO_SGR=1 MANPAGER="sh -c 'col -bx | bat -plman --theme \"Catppuccin Mocha\"'" command man "$@"; }

_help_accept_line() {
    local original="$BUFFER"
    local -a words
    local i

    # Parse the line like Zsh
    words=("${(z)original}")

    # Not enough parameters to contain --help
    (( ${#words} < 2 )) && {
        zle .accept-line
        return
    }

    # Look for ten exact match for --help
    for (( i = 2; i <= ${#words}; i++ )); do
        if [[ "${words[i]}" == "--help" ]]; then
            # Avoid a double transformation
            if [[ "$original" != *'| bat -plhelp'* ]]; then
                BUFFER="${original} 2>&1 | bat -plhelp"
            fi
            break
        fi
    done

    zle .accept-line
}

zle -N accept-line _help_accept_line
alias -g -- -h='-h 2>&1 | bat -plhelp'

export FZF_DEFAULT_OPTS='--height 80% --layout=reverse --border=rounded --prompt="  " --pointer="  " --preview-window=right:65%:wrap:border-left'
export FZF_DEFAULT_COMMAND='fd --type f --hidden --strip-cwd-prefix --exclude .git --exclude .venv --exclude node_modules'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
# Deduplicated PATH setup
typeset -U path
path=(
  $HOME/.local/bin
  $HOME/.fzf/bin
  $path
  $HOME/.pdtm/go/bin
)
path=($^path(N-/))
export PATH