# === Environment & PATH ===
export EDITOR=nvim
export VISUAL=nvim
export BROWSER=google-chrome-stable
export PAGER="bat -p --color auto"
export TERMINAL=kitty
export TERM="xterm-256color"
export GPG_TTY=$TTY
export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME/ripgrep/ripgreprc"
export ATUIN_TMUX_POPUP=false

typeset -U path
path=(
  $HOME/.local/bin
  $HOME/.fzf/bin
  $HOME/.pdtm/go/bin
  $path
)
path=($^path(N-/))
export PATH

fpath=(
  $XDG_CONFIG_HOME/zsh/completions
  $fpath
)


# === History & Shell Options ===
HISTFILE=~/.zsh_history
HISTSIZE=100000
SAVEHIST=100000
setopt APPEND_HISTORY SHARE_HISTORY HIST_IGNORE_DUPS HIST_IGNORE_SPACE HIST_EXPIRE_DUPS_FIRST HIST_FIND_NO_DUPS histverify extendedhistory
setopt extended_glob AUTOCD NUMERIC_GLOB_SORT
setopt AUTOPUSHD PUSHD_IGNORE_DUPS PUSHD_MINUS

# === Keybindings & Line Editor ===
bindkey -e

bindkey '^[[1~' beginning-of-line    # Home
bindkey '^[[H'  beginning-of-line    # Home
bindkey '^[[3~' delete-char          # Delete
bindkey '^[[4~' end-of-line          # End
bindkey '^[[F'  end-of-line          # End
bindkey '^[[5~' up-line-or-history   # PageUp
bindkey '^[[6~' down-line-or-history # PageDown
bindkey '^?'    backward-delete-char # Backspace

FULLWORDCHARS="*?_-.,[]~=/&:;!#$%^(){}<>'\""
backward-full-word() { WORDCHARS=$FULLWORDCHARS zle .backward-word ; }
backward-sub-word() { WORDCHARS="" zle .backward-word ; }
forward-full-word() { WORDCHARS=$FULLWORDCHARS zle .forward-word ; }
forward-sub-word() { WORDCHARS="" zle .forward-word ; }
backward-kill-full-word() { WORDCHARS=$FULLWORDCHARS zle .backward-kill-word ; }
backward-kill-sub-word() { WORDCHARS="" zle .backward-kill-word ; }
forward-kill-full-word() { WORDCHARS=$FULLWORDCHARS zle .kill-word ; }
forward-kill-sub-word() { WORDCHARS="" zle .kill-word ; }

zle -N backward-full-word
zle -N backward-sub-word
zle -N forward-full-word
zle -N forward-sub-word
zle -N backward-kill-full-word
zle -N backward-kill-sub-word
zle -N forward-kill-full-word
zle -N forward-kill-sub-word

# Jumping:
bindkey "^[^b"    backward-full-word       # Ctrl + Alt + B
bindkey '^[[1;7D' backward-full-word       # Ctrl + Alt + Left
bindkey "^[b"     backward-sub-word        # Alt + B
bindkey '^[[1;5D' backward-sub-word        # Ctrl + Left
bindkey "^[f"     forward-sub-word         # Alt + F
bindkey '^[[1;5C' forward-sub-word         # Ctrl + Right
bindkey "^[^f"    forward-full-word        # Ctrl + Alt + F
bindkey '^[[1;7C' forward-full-word        # Ctrl + Alt + Right
# Deleting:
bindkey "^[^h"    backward-kill-sub-word   # Ctrl + Alt + H
bindkey "^w"      backward-kill-full-word  # Ctrl + W
bindkey "^[d"     forward-kill-sub-word    # Alt + D
bindkey "^[^d"    forward-kill-full-word   # Ctrl + Alt + D


autoload -Uz up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey '^[[A' up-line-or-beginning-search
bindkey '^[[B' down-line-or-beginning-search

autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^X^E' edit-command-line
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward
autoload -Uz zmv

# === Fast Static Cache Loading ===
local main_cache="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/all_inits.zsh"

[[ -f "$main_cache" ]] && source "$main_cache"

rebuild-zsh-cache() {
  local cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/zsh"
  mkdir -p "$cache_dir"
  echo "Rebuilding consolidated Zsh cache..."

  {
    echo '(( $+functions[compdef] )) || compdef() { : }'
    (( $+commands[mise] )) && { mise env|rg -v PATH;mise activate --shims; }
    (( $+commands[fzf] )) && fzf --zsh
    (( $+commands[zoxide] )) && zoxide init zsh
    (( $+commands[atuin] )) && atuin init zsh --disable-up-arrow
    (( $+commands[exegol] )) && register-python-argcomplete --no-defaults exegol
    (( $+commands[oh-my-posh] )) && oh-my-posh init zsh --config ~/.config/oh-my-posh/clomic.toml; echo
    # (( $+commands[oh-my-posh] )) && oh-my-posh init zsh --config ~/.config/oh-my-posh/skillarch.  toml; echo
    (( $+commands[uv] )) && uv generate-shell-completion zsh
    (( $+commands[wt] )) && wt config shell init zsh
  } > "$main_cache"
  zcompile "$main_cache"

  dircolors -p > ~/.cache/zsh/dircolors

  (( $+commands[carapace] )) && carapace _carapace zsh > "$cache_dir/carapace.zsh"
  zcompile "$cache_dir/carapace.zsh"

  echo "Cache rebuilt successfully into $main_cache!"
}

# === Load zsh-defer ===
[[ -f ~/.local/share/zsh-defer/zsh-defer.plugin.zsh ]] && source ~/.local/share/zsh-defer/zsh-defer.plugin.zsh

# === Load Plugins (via zsh-defer) ===
_load_plugins() {
  ZSH_AUTOSUGGEST_STRATEGY=(history completion)
  zle_highlight=('paste:none')

  [[ -f ~/.local/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]] && \
    source ~/.local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

  [[ -f ~/.local/share/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh ]] && \
    source ~/.local/share/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
}
(( $+functions[zsh-defer] )) && zsh-defer _load_plugins || _load_plugins

# === Completion Styling ===
autoload -Uz compinit
local zcompdump="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/zcompdump"
if [[ -n "$zcompdump(#qN.m+1)" ]]; then
  compinit -i -d "$zcompdump"
  { zcompile "$zcompdump" } &!
else
  compinit -C -i -d "$zcompdump"
fi


local carapace_cache="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/carapace.zsh"
[[ -f "$carapace_cache" ]] && source "$carapace_cache"
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]-_}={[:upper:][:lower:]_-}' 'r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu select
compdef _cd cd

# === Helpers, Aliases & FZF ===
if [[ -r ~/.cache/zsh/dircolors ]]; then
  eval "$(dircolors -b ~/.cache/zsh/dircolors)"
fi

export FZF_DEFAULT_OPTS='--height 80% --layout=reverse --border=rounded --prompt="  " --pointer="  " --preview-window=right:65%:wrap:border-left'
export FZF_DEFAULT_COMMAND='fd --type f --hidden --strip-cwd-prefix --exclude .git --exclude .venv --exclude node_modules'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

man() { GROFF_NO_SGR=1 MANPAGER="sh -c 'col -bx | bat -plman'" command man "$@"; }

_help_accept_line() {
    local original="$BUFFER"
    local -a words
    words=("${(z)original}")

    (( ${#words} < 2 )) && { zle .accept-line; return; }

    for (( i = 2; i <= ${#words}; i++ )); do
        if [[ "${words[i]}" == "--help" ]]; then
            if [[ "$original" != *'| bat -plhelp'* ]]; then
                BUFFER="${original} 2>&1 | bat -plhelp"
            fi
            break
        fi
    done
    zle .accept-line
}

zle -N accept-line _help_accept_line
alias -g -- -h='-h 2>&1 | bat -plhelp'

# SSH-agent
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
# for key in ~/.ssh/id_*; do [[ -f "$key" ]] && ssh-add "$key" 2>/dev/null; done; unset key

# Intégration différée des aliases annexes
_load_aliases() {
  [[ -f /opt/skillarch/config/aliases ]] && source /opt/skillarch/config/aliases
  [[ -f ~/.my_aliases ]] && source ~/.my_aliases
}
(( $+functions[zsh-defer] )) && zsh-defer _load_aliases || _load_aliases

path=(
  $HOME/.local/go/bin
  $HOME/.cache/.bun/bin
  $path
)